@MovieMateAPI_HostAddress = http://localhost:5113

GET {{MovieMateAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MovieMateAPI_HostAddress}}/samples
Accept: application/json

###



GET {{MovieMateAPI_HostAddress}}/
Accept: application/json

###
